	
PROC SQL ;

/*Create Temp table to load the extracted Data*/

OPTIONS MISSING='';

CREATE TABLE WORK.LKTHRU AS 

			SELECT 
					'03 - Lookthrough' AS DATA_SOURCE LENGTH=40				

					, CASE
						WHEN COALESCE(LK_THRG.LOOKTHROUGH_CUSIP,LK_THRG.LOOKTHROUGH_ALTERNATIVE_ID,'NA') = 'NA'  
							THEN 
								CASE 
									WHEN LENGTH(TRIM(LK_THRG.LOOKTHROUGH_ISIN)) = 14 
										THEN TRIM(SUBSTR(LK_THRG.LOOKTHROUGH_ISIN,3,9))||TRIM(SUBSTR(LOOKTHROUGH_ISIN,13,2))||'-'||TRIM(CPRTY.COUNTERPARTY_ID)
									ELSE 
										TRIM(SUBSTR(LOOKTHROUGH_ISIN,3,10))||'-'||TRIM(CPRTY.COUNTERPARTY_ID)
								END 
							ELSE 
						 		TRIM(COALESCE(LK_THRG.LOOKTHROUGH_CUSIP,LK_THRG.LOOKTHROUGH_ALTERNATIVE_ID))||'-'||TRIM(CPRTY.COUNTERPARTY_ID)
				      END AS CUSIP LENGTH=500

					, F.PORTFOLIO_ID AS PORTF_LIST

					, XIP.ENTITY_NAME AS PORTF_NAME

					, LK_THRG.PARENT_CUSIP AS PARENT_CUSIP

					, LK_THRG.PARENT_ISIN AS PARENT_ISIN

					, PUT(XFPC.X_PXS_DT,DDMMYY10.) AS PXS_DATE

					, LK_THRG.SM_SEC_GROUP AS SM_SEC_GROUP

					, LK_THRG.SM_SEC_TYPE

					, CASE
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '000' THEN 'ZERO'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '001' THEN 'FIXED'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '002' AND  F.PORTFOLIO_ID <> 'A_320NONBR' THEN 'FLOAT'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '002' AND  F.PORTFOLIO_ID = 'A_320NONBR' THEN 'FLOATING'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '003' THEN 'MAT'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '004' THEN 'N/A'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '005' THEN 'FIXED TO FLOAT'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '006' THEN 'FLOAT TO FIXED'
						WHEN A.INTEREST_PAYMENT_TYPE_CD = '099' THEN ''
						ELSE 'UNKNOWN' 
						END
					  AS SM_CPN_TYPE

					, RF.RISK_FACTOR_ID AS RESET_INDEX

					, LK_THRG.COUNTRY AS COUNTRY

					, LK_THRG.CURRENCY AS CURRENCY
										
					, ( ( LK_THRG.PCT_OF_FUND * F.X_MARKET_VALUE ) / 100) AS MKT_VALUE FORMAT = 21.2 LABEL = 'MKT_VALUE'

					, ( ( ( LK_THRG.PCT_OF_FUND * F.X_MARKET_VALUE ) / 100) /1000) AS MKT_VALUE_DIV_1000 FORMAT = 21.4

					, LK_THRG.PAR_FACE_VALUE AS GBP_CUR_FACE FORMAT = 21.4

					, LK_THRG.PAR_FACE_VALUE/1000 AS GBP_CUR_FACE_DIV_1000 FORMAT = 21.6

					/* Not using the below 
					, ( LK_THRG.PAR_FACE_VALUE * ( F.X_SOLVENCY_II_VALUE  / PRNT_CONS.SOL_VAL ) ) AS GBP_CUR_FACE FORMAT = 21.4

					,  ( ( LK_THRG.PAR_FACE_VALUE * ( F.X_SOLVENCY_II_VALUE  / PRNT_CONS.SOL_VAL ) ) / 1000 ) AS GBP_CUR_FACE_DIV_1000 FORMAT = 21.6

					*/

					, LK_THRG.YIELD_PCT/100*100 AS COUPON

					, A.PAYMENT_RESET_FREQ_MONTH_NO  AS COUPON_FREQUENCY

					, PUT(A.FIRST_PAYMENT_DT,DDMMYY10.) AS NEXT_COUPON

					, LK_THRG.MOD_DUR AS MOD_DUR

					, LK_THRG.SPREAD_DUR  AS  SPREAD_DUR

					, LK_THRG.YIELD_PCT/100*100 AS YIELD_TO_MAT

					, PUT(LK_THRG.MATURITY_DT,DDMMYY10.) AS MATURITY_DATE

					, PUT(LK_THRG.MATURITY_DT,DDMMYY10.) AS ZV_MATURITY_DATE

					, LK_THRG.LOOKTHROUGH_NAME AS SHORT_STD_DESC LENGTH=250 FORMAT=$250.
																											
					, CPRTY.COUNTERPARTY_ID AS ULTIMATE_PARENT_TICKER

					, COALESCE(ULTMT_COUNTERPARTY_NM,LK_THRG.LOOKTHROUGH_NAME) AS ULT_ISSUER_NAME LABEL = 'ULT_ISSUER_NAME'  INFORMAT = $255. FORMAT=$255.

					, COALESCE(LK_THRG.COUNTERPARTY_NM,LK_THRG.LOOKTHROUGH_NAME) AS ISSUER_NAME  LABEL = 'ISSUER_NAME'  INFORMAT = $255. FORMAT=$255.

					/*CHANGING FOR CONCENTRATION RISK , NO LEHM RATING IS REQUIRED , TAKE THE AVE RATING INSTEAD*/
					/*CHANGING FOR CONCENTRATION RISK - FOR LOOK THRU AVE RATING IS TAKEN INSTEAD OF LEHM_RATING*/
					, SNP_DERIV.ASSESSMENT_GRADE  AS LEHM_RATING_TXT LENGHT =20

					, XFPC.X_LEHM_ISS_RATING_TXT AS LEHM_RATING_ISS

					, SNP_DERIV.ASSESSMENT_GRADE AS AVE_RATING

					, XFPC.X_BARC_FOUR_PILLAR_SECTOR      AS BARCLAYS_FOUR_PILLAR_SECTOR

					, XFPC.X_BARC_FOUR_PILLAR_SUBSECTOR AS  BARCLAYS_FOUR_PILLAR_SUBSECTOR

					, XFPC.X_BARC_FOUR_PILLAR_INDUSTRY  AS BARCLAYS_FOUR_PILLAR_INDUSTRY  

					, XFPC.X_BARC_FOUR_PILLAR_SUBINDUSTRY AS BARCLAYS_FOUR_PILLAR_SUBINDUSTRY 

					, XFPC.X_INFL AS INFL

					, XFPC.X_INTERNAL_RATING  AS INTERNAL_RATING     

					, LK_THRG.LOOKTHROUGH_ISIN  AS ISIN

					, EMB.EMBEDDED_OPTION_TYPE_CD  AS PUT_CALL

					, LK_THRG.CIC AS CIC       

					, ( ( LK_THRG.PCT_OF_FUND * F.X_MARKET_VALUE ) / 100) AS PAM_MV FORMAT = 21.2 LABEL = 'PAM_MV'

					, LK_THRG.PAR_FACE_VALUE AS GBP_CONV_CUR_FACE FORMAT = 21.2 

					/*, ( ( LK_THRG.PAR_FACE_VALUE * F.X_SOLVENCY_II_VALUE ) / PRNT_CONS.SOL_VAL ) AS GBP_CONV_CUR_FACE FORMAT = 21.2 
					DONT USE*/

					, CPRTY.COUNTERPARTY_ID AS TICKER

					, 0.0 AS MKT_NOTION FORMAT=21.2

					, '' AS X_PAM_GL_GRP LENGTH=100

					, CASE WHEN CURRENCY = 'GBP' THEN 1.0 ELSE 0.0 END AS I_T_CURRENCY_RATE  LABEL = 'EXC_RATES'

					, A.X_I_T_INV_CLS_GROUP_OVRD  AS I_T_CLS_GRP 
					, A.X_I_T_INV_CLS_CATEGORY_OVRD  AS I_T_CLS_CAT 
					, A.X_EXPERT_JUDGEMENT_FIN_INV_CLS AS FIN_INV_CLS  

					, LK_THRG.RTG_MOODYS AS RTG_MOODYS
					, COALESCE(MDY_RAT.ASSESSMENT_SCORE_NO,0)	 AS MDY_SCORE	
					/*, MDY_RAT.X_SOLII_CREDIT_QUALITY_VAL AS MDY_SII_CREDIT_QLTY_VAL */

					, LK_THRG.RTG_SP AS RTG_SP	
					, COALESCE(SP_RAT.ASSESSMENT_SCORE_NO,0) AS SP_SCORE		 
					/*, SP_RAT.X_SOLII_CREDIT_QUALITY_VAL AS SP_RAT_SII_CREDIT_QLTY_VAL */

					, LK_THRG.RTG_FITCH AS RTG_FITCH
					, COALESCE(FIT_RAT.ASSESSMENT_SCORE_NO,0) AS FIT_SCORE
					/*, FIT_RAT.X_SOLII_CREDIT_QUALITY_VAL AS FIT_RAT_SII_CREDIT_QLTY_VAL */

					, COALESCE(SOLII_RAT.ASSESSMENT_SCORE_NO,0) AS  WTFL_SCORE
					, LK_THRG.SOLII_CREDIT_RTG AS WTFL_GRADE
					, CASE 
						WHEN LK_THRG.SOLII_CREDIT_RTG = LK_THRG.RTG_SP AND SOLII_RAT.X_SOLII_CREDIT_QUALITY_VAL  = SP_RAT.X_SOLII_CREDIT_QUALITY_VAL  THEN 'SP'
						WHEN LK_THRG.SOLII_CREDIT_RTG = LK_THRG.RTG_MOODYS AND SOLII_RAT.X_SOLII_CREDIT_QUALITY_VAL  = MDY_RAT.X_SOLII_CREDIT_QUALITY_VAL THEN 'MDY'
						WHEN LK_THRG.SOLII_CREDIT_RTG = LK_THRG.RTG_FITCH AND SOLII_RAT.X_SOLII_CREDIT_QUALITY_VAL  = FIT_RAT.X_SOLII_CREDIT_QUALITY_VAL THEN 'FIT'				
							ELSE 'UNK'
						END AS WTFL_AGENCY
					, SNP_DERIV.ASSESSMENT_GRADE AS SNP_EQUI_RATING

					, CASE
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'AA+' THEN 'AA'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'AA-' THEN  'AA'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'A+' THEN 'A'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'A-'  THEN 'A'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'BBB+'  THEN 'BBB'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'BBB-'  THEN 'BBB'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'BB+'  THEN 'BB'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'BB-'  THEN 'BB'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'B+'  THEN 'B'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'B-'  THEN 'B'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'CCC+'  THEN 'CCC'
						WHEN SNP_DERIV.ASSESSMENT_GRADE = 'CCC-'  THEN 'CCC'
						ELSE SNP_DERIV.ASSESSMENT_GRADE
						END
					 AS GROUPED_RATING

					, SOLII_RAT.X_SOLII_CREDIT_QUALITY_VAL AS WTFL_SII_CREDIT_QLTY_VAL

					, X_EEA_MEMBER_FLAG
					, X_OECD_MEMBER_FLAG

					, CASE 
						WHEN LK_THRG.CIC = 'XL52' AND  LK_THRG.TIER_TYPE  = '' THEN  'TYPE 2' 
						ELSE LK_THRG.TIER_TYPE 
					  END AS X_SECURITISED_CREDIT_TYPE

					 , '' AS  INFRASTRUCTURE_INV_CD LENGTH = 10

					, LK_THRG.SCRTY_IND_SCTR AS NACE

					, '' AS 	X_STRUCTURE LENGTH=50

					, XFPC.X_MOD_DUR_S2 AS MOD_DUR_S2 /*Added for Interest rate risk*/

					, CASE /*Added for CPARTY  risk*/
						WHEN LK_THRG.ULTMT_COUNTERPARTY_LEI_STATUS<> '1' THEN 'None'																														
						ELSE TRIM('LEI/')||TRIM(ULTMT_COUNTERPARTY_LEI_CD)
					  END AS ULT_ISSUER_LEI LENGTH = 100

					, CASE 	/*Added for CPARTY  risk*/
						WHEN LK_THRG.COUNTERPARTY_LEI_STATUS<> '1' THEN 'None'																														
						ELSE TRIM('LEI/')||TRIM(COUNTERPARTY_LEI_CD)
					  END AS ISSUER_LEI LENGTH = 100


					/*	, LK_THRG.COUNTERPARTY_NM AS GRPD_NAME   (Not Reqrd)*/

			FROM 
				Test.X_FUND_LOOK_THROUGH LK_THRG

			INNER JOIN 																						
				test.FINANCIAL_INSTRUMENT A																						
				ON 																						
				A.FINANCIAL_INSTRUMENT_RK = LK_THRG.FINANCIAL_INSTRUMENT_RK																					
				AND DATEPART(A.VALID_FROM_DTTM)	<= &AS_AT_MTH
				AND DATEPART(A.VALID_TO_DTTM)	> &AS_AT_MTH

			INNER JOIN 																						
				test.FINANCIAL_POSITION F																						
				ON 
				F.FINANCIAL_INSTRUMENT_RK = A.FINANCIAL_INSTRUMENT_RK																						
				AND DATEPART(F.VALID_FROM_DTTM)	<= &AS_AT_MTH	
				AND DATEPART(F.VALID_TO_DTTM) >	&AS_AT_MTH	
																																															
			INNER JOIN																						
				test.X_INVESTMENT_PORTFOLIO XIP																						
				ON																						
				XIP.PORTFOLIO_ID = F.PORTFOLIO_ID 																				
				AND PUT(DATEPART(XIP.VALID_TO_DTTM),DATE9.) = '31DEC9999' 

			LEFT JOIN /*join on X_FINANCIAL_POSITION_CHNG*/
				test.X_FINANCIAL_POSITION_CHNG XFPC																															
					ON																															
			         	F.FINANCIAL_POSITION_RK = XFPC.FINANCIAL_POSITION_RK
						AND DATEPART(XFPC.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
				  		AND DATEPART(XFPC.VALID_TO_DTTM) > &AS_AT_MTH 

			LEFT JOIN 
				test.COUNTERPARTY CPRTY
				ON 
				A.ISSUER_COUNTERPARTY_RK = CPRTY.COUNTERPARTY_RK
				AND DATEPART(CPRTY.VALID_FROM_DTTM)	<= &AS_AT_MTH	
				AND DATEPART(CPRTY.VALID_TO_DTTM) >	&AS_AT_MTH	
				AND UPCASE(CPRTY.X_LEH_SUBSECTOR_CD) <> 'ABS'

			LEFT JOIN 																															
				test.FINANCIAL_INSTRUMENT_ISSUE B /* ISIN */																															
				ON  A.FINANCIAL_INSTRUMENT_RK = B.FINANCIAL_INSTRUMENT_RK																															
				AND DATEPART(B.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
				AND DATEPART(B.VALID_TO_DTTM) > &AS_AT_MTH 																														
				AND B.ISSUE_TYPE_CD = '001'

			LEFT JOIN 																						
				test.EMBEDDED_OPTIONS EMB /* EMB */
				ON  A.FINANCIAL_INSTRUMENT_RK = EMB.FINANCIAL_INSTRUMENT_RK																						
				AND DATEPART(EMB.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
				AND DATEPART(EMB.VALID_TO_DTTM) > &AS_AT_MTH

			/*Get the Fitch Rating Details*/			
			LEFT JOIN
				(
				SELECT DISTINCT 
				ASSESSMENT_GRADE,
				ASSESSMENT_SCORE_NO,
				X_SOLII_CREDIT_QUALITY_VAL
				FROM 
				test.ASSESSMENT_RATING_GRADE 
				WHERE
				ASSESSMENT_AGENCY_CD = 'FIT'
				AND PUT(DATEPART(VALID_TO_DTTM),DATE9.) = '31DEC4747'
				) FIT_RAT

				ON LK_THRG.RTG_FITCH = FIT_RAT.ASSESSMENT_GRADE	

			/*Get the Moody's Rating Details*/	
			LEFT JOIN
				(
				SELECT DISTINCT 
				ASSESSMENT_GRADE,
				ASSESSMENT_SCORE_NO,
				X_SOLII_CREDIT_QUALITY_VAL
				FROM 
				test.ASSESSMENT_RATING_GRADE 
				WHERE 
				ASSESSMENT_AGENCY_CD = 'MDY'
				AND PUT(DATEPART(VALID_TO_DTTM),DATE9.) = '31DEC4747'
				) MDY_RAT

				ON 	LK_THRG.RTG_MOODYS = MDY_RAT.ASSESSMENT_GRADE	

			/*Get the SNP Rating Details*/	
			LEFT JOIN 
				(
				SELECT DISTINCT 
				ASSESSMENT_GRADE,
				ASSESSMENT_SCORE_NO ,
				X_SOLII_CREDIT_QUALITY_VAL
				FROM 
				test.ASSESSMENT_RATING_GRADE 
				WHERE 
				ASSESSMENT_AGENCY_CD = 'S_P'
				AND PUT(DATEPART(VALID_TO_DTTM),DATE9.) = '31DEC4747'	
				) SP_RAT

				ON 		LK_THRG.RTG_SP = SP_RAT.ASSESSMENT_GRADE		

			/*Get the Calculated Waterfall Rating Details*/			
			LEFT JOIN
				(
				SELECT DISTINCT 
				ASSESSMENT_GRADE,
				ASSESSMENT_SCORE_NO,
				X_SOLII_CREDIT_QUALITY_VAL
				FROM 
				test.ASSESSMENT_RATING_GRADE 
				WHERE
				 PUT(DATEPART(VALID_TO_DTTM),DATE9.) = '31DEC4747'
				 AND ASSESSMENT_AGENCY_CD <> 'OTH'
				) SOLII_RAT

				ON 		LK_THRG.SOLII_CREDIT_RTG = SOLII_RAT.ASSESSMENT_GRADE	
				AND 	LK_THRG.SOLII_CREDIT_QUALITY_VAL = SOLII_RAT.X_SOLII_CREDIT_QUALITY_VAL

			LEFT JOIN 																															
				test.FINANCIAL_INSTRUMENT_ISSUE C /* CUSIP */																															
			  	ON  A.FINANCIAL_INSTRUMENT_RK = C.FINANCIAL_INSTRUMENT_RK																															
				AND DATEPART(C.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
				AND DATEPART(C.VALID_TO_DTTM) > &AS_AT_MTH 																														
				AND C.ISSUE_TYPE_CD = '003'	

			LEFT JOIN  /* CIC*/																															
			(																															
				SELECT																														
					 		A2.FINANCIAL_INSTRUMENT_RK																											
				 		  , A2.VALID_FROM_DTTM																												
				 		  , A2.VALID_TO_DTTM																												
				 		  , A2.ISSUE_CD																												
				 		  , A2.ISSUE_TYPE_CD					 		  																					
				FROM																														
				(																														
				 SELECT																														
				 			TICK2.FINANCIAL_INSTRUMENT_RK																											
				 		  , MAX(TICK2.VALID_FROM_DTTM) AS VALID_FROM_DTTM																												
				 		  , TICK2.ISSUE_TYPE_CD																												
					FROM																													
							 test.FINANCIAL_INSTRUMENT TICK1																											
					       , test.FINANCIAL_INSTRUMENT_ISSUE TICK2																													
				  WHERE																														
				  			  TICK1.FINANCIAL_INSTRUMENT_RK = TICK2.FINANCIAL_INSTRUMENT_RK																											
								AND DATEPART(TICK2.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
								AND DATEPART(TICK2.VALID_TO_DTTM) > &AS_AT_MTH 																													
								AND TICK2.ISSUE_TYPE_CD = '002'																													
				 GROUP BY																														
				 			TICK2.FINANCIAL_INSTRUMENT_RK																											
				 		  , TICK2.ISSUE_TYPE_CD																												
				  ) A1  																														
				, test.FINANCIAL_INSTRUMENT_ISSUE A2																														
				WHERE 																														
					  A1.FINANCIAL_INSTRUMENT_RK = A2.FINANCIAL_INSTRUMENT_RK																										
					  AND A1.VALID_FROM_DTTM = A2.VALID_FROM_DTTM																													
					  AND A1.ISSUE_TYPE_CD = A2.ISSUE_TYPE_CD	 																												
			) CIC																															
			  ON  A.FINANCIAL_INSTRUMENT_RK = CIC.FINANCIAL_INSTRUMENT_RK																															
			  AND CIC.ISSUE_TYPE_CD = '002'	

			LEFT JOIN 
				test.RISK_FACTOR_X_EXPOSURE RF
				ON RF.RISK_FACTOR_ID <> ''
				AND A.FINANCIAL_INSTRUMENT_RK = RF.FINANCIAL_INSTRUMENT_RK
				AND DATEPART(RF.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
				AND DATEPART(RF.VALID_TO_DTTM) > &AS_AT_MTH


			LEFT JOIN 	
				test.COUNTRY CNTRY
					ON  ( LK_THRG.COUNTRY = CNTRY.COUNTRY_CD
					AND PUT(DATEPART(CNTRY.VALID_TO_DTTM),DATE9.) = '31DEC9999')  

			LEFT JOIN 
				(
					SELECT 

					C.ISSUE_CD AS CUSIP,
					SUM(FP.X_SOLVENCY_II_VALUE) AS SOL_VAL

					FROM 

					test.FINANCIAL_INSTRUMENT A			

						INNER JOIN 																						
							test.FINANCIAL_POSITION FP																						
							ON 
							FP.FINANCIAL_INSTRUMENT_RK = A.FINANCIAL_INSTRUMENT_RK																						
							AND DATEPART(FP.VALID_FROM_DTTM)	<= &AS_AT_MTH	
							AND DATEPART(FP.VALID_TO_DTTM) >	&AS_AT_MTH		

						LEFT JOIN 																															
							test.FINANCIAL_INSTRUMENT_ISSUE C /* CUSIP */																															
						  	ON  A.FINANCIAL_INSTRUMENT_RK = C.FINANCIAL_INSTRUMENT_RK																															
							AND DATEPART(C.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
							AND DATEPART(C.VALID_TO_DTTM) > &AS_AT_MTH 																														
							AND C.ISSUE_TYPE_CD = '003'	

					WHERE 																					
						DATEPART(A.VALID_FROM_DTTM) <= &AS_AT_MTH 																						
						AND DATEPART(A.VALID_TO_DTTM) > &AS_AT_MTH 		
						AND A.X_EXPERT_JUDGEMENT_FIN_INV_CLS = 'Investment Funds'					
						AND A.X_I_T_INV_CLS_GROUP_OVRD <> 'Exclude'

				GROUP BY 
				C.ISSUE_CD
			) PRNT_CONS	
			  ON LK_THRG.PARENT_CUSIP  = PRNT_CONS.CUSIP

			LEFT JOIN 
					(
						SELECT 
							DISTINCT 
							ASSESSMENT_AGENCY_CD,
							ASSESSMENT_GRADE,
							ASSESSMENT_SCORE_NO,
							X_SOLII_CREDIT_QUALITY_VAL
						FROM 
							test.ASSESSMENT_RATING_GRADE 
						WHERE 
							ASSESSMENT_AGENCY_CD = 'S_P' 
							AND SHORTTERM_FLG = '0'
							AND PUT(DATEPART(VALID_TO_DTTM),DATE9.) = '31DEC4747'	
							AND UPCASE(ASSESSMENT_GRADE) NOT IN ('GOVT','GOVT EQUIV','AGENCY')
							AND MODEL_RK = 1
					)SNP_DERIV
				ON 	SOLII_RAT.ASSESSMENT_SCORE_NO = SNP_DERIV.ASSESSMENT_SCORE_NO
				 	
	
																				
			WHERE 
				LK_THRG.AS_AT_DT = &AS_AT_MTH
				AND DATEPART(LK_THRG.VALID_FROM_DTTM) <= &AS_AT_MTH	
				AND DATEPART(LK_THRG.VALID_TO_DTTM)> &AS_AT_MTH;
QUIT;
