/* RUN direct from Main Tables*/
PROC SQL ;

/*Create Temp table to load the extracted Data*/

CREATE TABLE WORK.SF_PROPERTY_RSK AS 

	SELECT
		
		CASE 	
			WHEN A.SOURCE_SYSTEM_CD = 'BLR' THEN '01 - Blackrock - Without Lookthrough'
			ELSE '02 - Non Blackrock - Without Lookthrough'
		 END AS DATA_SOURCE
				
		, A.PORTFOLIO_ID AS PORTF_LIST

		, XIP.ENTITY_NAME AS PORTF_NAME

		, CASE
			WHEN PHY.PHYSICAL_ASSET_ID = 'BRSGA8C52' AND X_PHY.CIC_CD ='XT91' THEN 'BRSGA8C52-A'
			WHEN PHY.PHYSICAL_ASSET_ID = 'BRSGA8C52' AND X_PHY.CIC_CD ='XT92' THEN 'BRSGA8C52-B'
			ELSE PHY.PHYSICAL_ASSET_ID 
		   END AS UNIQUE_IDENTIFIER

		, PHY.X_ISSUER_NM AS ISSUER_NAME

		, A.CURRENCY_CD AS CURRENCY

		, CASE 
			WHEN SUBSTR(X_PHY.CIC_CD,3,2) IN ('93','95','96') 
				THEN 'Y' 
			ELSE 'N' 
		  END AS PPTY_FOR_OWN_USE

		, X_PHY.APPRAISED_AMT/1000 AS MKT_VALUE_DIV_1000 FORMAT=21.2

		, X_PHY.APPRAISED_AMT AS MKT_VALUE FORMAT=21.2

		, CASE 
			WHEN PHY.PHYSICAL_ASSET_ID LIKE '%OLUKI-%' THEN '0'
			ELSE '1'
		  END AS PRPTY_RSK_SCOPE

		, 'FUND' AS SM_SEC_GROUP

		, 'REIT' AS SM_SEC_TYPE 

		, X_PHY.CIC_CD AS CIC

	FROM       				
		test.FINANCIAL_POSITION A

	INNER JOIN 		
		test.PHYSICAL_ASSET PHY
			ON A.PHYSICAL_ASSET_RK = PHY.PHYSICAL_ASSET_RK
	 		AND DATEPART(PHY.VALID_FROM_DTTM)	<= &AS_AT_MTH  
			AND DATEPART(PHY.VALID_TO_DTTM)	> &AS_AT_MTH     

	INNER JOIN 			
		test.X_PHYSICAL_ASSET X_PHY
			ON A.PHYSICAL_ASSET_RK = X_PHY.PHYSICAL_ASSET_RK
	 		AND DATEPART(X_PHY.VALID_FROM_DTTM)	<= &AS_AT_MTH  
			AND DATEPART(X_PHY.VALID_TO_DTTM)	> &AS_AT_MTH 

	INNER JOIN  		
		test.X_I_T_INT_EXC_RATES EXC
			ON A.CURRENCY_CD = EXC.CURRENCY_CD
	 		AND DATEPART(EXC.VALID_FROM_DTTM)	<= &AS_AT_MTH  
			AND DATEPART(EXC.VALID_TO_DTTM)	> &AS_AT_MTH       

	LEFT JOIN 			
		test.X_FINANCIAL_POSITION_CHNG     XFPC
			ON A.FINANCIAL_POSITION_RK = XFPC.FINANCIAL_POSITION_RK       
	 		AND DATEPART(XFPC.VALID_FROM_DTTM)	<= &AS_AT_MTH  
			AND DATEPART(XFPC.VALID_TO_DTTM)	> &AS_AT_MTH 

	LEFT JOIN    		
		test.X_INVESTMENT_PORTFOLIO XIP    
			ON  ( XIP.PORTFOLIO_ID = A.PORTFOLIO_ID   
			AND  PUT(DATEPART(XIP.VALID_TO_DTTM),DATE9.) = '31DEC9999' )   

	LEFT JOIN 	
		test.COUNTRY CNTRY
			ON  ( X_PHY.ASSET_LOCATION_COUNTRY_CD = CNTRY.COUNTRY_CD
			AND PUT(DATEPART(CNTRY.VALID_TO_DTTM),DATE9.) = '31DEC9999')   

	WHERE     
	 	DATEPART(A.VALID_FROM_DTTM)	<= &AS_AT_MTH  
		AND DATEPART(A.VALID_TO_DTTM)	> &AS_AT_MTH 

	ORDER BY 
		DATA_SOURCE
		, PORTF_LIST
		, UNIQUE_IDENTIFIER

;

QUIT;

/*------------------
	 	AND DATEPART(PHY.VALID_FROM_DTTM)	<= &AS_AT_MTH  
		AND DATEPART(PHY.VALID_TO_DTTM)	> &AS_AT_MTH 
------------------*/