
/* RUN FROM Append */

PROC SQL ;

/*Create Temp table to load the extracted Data*/

OPTIONS MISSING='';

CREATE TABLE WORK.SF_CPARTY_RISK AS /*Including Counterparty risk for Derivatives and Cash*/


	SELECT

		PORTF_NAME

		, ISSUER_NAME

		, ISSUER_LEI
	
		, COALESCE(SNP_EQUI_RATING,'NR') AS SNP_EQUI_RATING_FIN

		, CASE 
			WHEN SUBSTR(CIC,3,1) IN ('A', 'E', 'D') THEN  '03. Derivatives, including 3rd party guarantees' 
			WHEN SUBSTR(CIC,3,1) IN ('7') THEN '04. Cash at bank'
			ELSE 'CIC APPROACH VIA LOOKTHRU'
		  END AS TYPE_OF_EXPOSURE

		, CASE 
			WHEN SUBSTR(CIC,3,1) IN ('A') THEN 'FUTURES' 
			WHEN SUBSTR(CIC,3,1) IN ('E') THEN 'FORWARDS' 
			WHEN SUBSTR(CIC,3,1) IN ('D') THEN 'INTEREST RATE SWAPS' 
			WHEN SUBSTR(CIC,3,1) IN ('7') THEN 'CASH'
			ELSE COALESCE(X_PAM_GL_GRP,'CIC APPROACH VIA LOOKTHRU')
		  END AS TYPE_OF_ASSET

		, CASE WHEN SUBSTR(CIC,3,1) IN ('7') THEN 'GBP'
				ELSE CURRENCY
		  END AS CURRENCY_FIN

		, SUM(MKT_VALUE) AS MKT_VALUE_FIN

		, SUM(MKT_VALUE_DIV_1000) AS MKT_VALUE_DIV_1000

		, CASE WHEN TRIM(PORTF_NAME) = 'DLG Legal Services Limited' THEN 'N' ELSE 'Y' END AS IN_GRP_GFLG


	FROM 
		WORK.SF_BASE_APPEND

	WHERE 
		 ( SUBSTR(CIC,3,1) IN ('A','E','D','7') AND UPCASE(I_T_CLS_GRP) NOT IN ('EXCLUDE') )
		 OR 
		 ( DATA_SOURCE = '03 - Lookthrough' AND SM_SEC_GROUP = 'CASH' AND SUBSTR(CIC,3,2) NOT IN ('23','24','E2','A2') ) 

	GROUP BY 
		PORTF_NAME
		, ISSUER_NAME
		, ISSUER_LEI
		, SNP_EQUI_RATING_FIN
		, TYPE_OF_EXPOSURE
		, TYPE_OF_ASSET
		, CURRENCY_FIN
		, IN_GRP_GFLG

	HAVING	 	
	 	SUM(MKT_VALUE)  <> 0 

	ORDER BY 
		TYPE_OF_EXPOSURE
		, TYPE_OF_ASSET
		, CURRENCY_FIN
		, SNP_EQUI_RATING_FIN


	;
QUIT;
