
PROC SQL ;

/*Create Temp table to load the extracted Data*/

OPTIONS MISSING='';

CREATE TABLE WORK.SF_CONCN_RSK AS 

	SELECT 

		CASE WHEN COUNTERPARTY LIKE '%PROPERTY-P5%' THEN 'PROPERTY-P5' ELSE COUNTERPARTY END AS COUNTERPARTY_FIN
		, TYPE_OF_EXPOSURE
		, CASE WHEN MIN(INPUT(CREDIT_RATING,2.))=. THEN 'NR' ELSE PUT(MIN(INPUT(CREDIT_RATING,2.)),2.) END AS CREDIT_RATING_FIN
		, SUM(MARKET_VALUE_D) AS MARKET_VALUE_FIN
		, SCOPE
		, PORTF_NAME
		, INC_GRP

	FROM 

		(
			SELECT
				DATA_SOURCE
				, CUSIP
				, PORTF_LIST
				, SUBSTR(CIC,3,2) AS CIC
				, UPCASE(CASE WHEN EXP_TYP = 'Type 4' THEN 'Property-'||REAL_TICKER_CONC_RSK ELSE ISSUER_NAME END) AS COUNTERPARTY
				, EXP_TYP AS TYPE_OF_EXPOSURE

				, CASE 
					WHEN  TRIM(PUT(ROUND(AVG(LEHM_SCORE)),2.)) = ''  OR SUBSTR(CIC,3,2) = '85' THEN 'NR' 
					ELSE   PUT(ROUND(AVG(LEHM_SCORE)),2.)
				  END  AS CREDIT_RATING

				, SUM(MKT_VALUE_DIV_1000) AS MARKET_VALUE_D
				, CONC_RSK AS SCOPE
				, PORTF_NAME
				, CASE 
					WHEN CUSIP LIKE '%_PART%' OR CUSIP LIKE 'INTERCO%' OR CUSIP LIKE 'OLU%' THEN 'N' 
					WHEN PORTF_NAME = 'DLG Legal Services Limited' THEN 'N'
					ELSE 'Y' 
				  END AS INC_GRP

			FROM 
				WORK.SF_FORECAST_ENGINE

			WHERE 
				SUBSTR(CIC_3_4_DIGIT,1,1) <> '4' 
				AND	UPCASE(I_T_CLS_GRP) <> 'EXCLUDE'
			/*	use the filter for Q2 alone to test the matching count , Teradata doesnt extract this record in Q2 as the Market value is 0.00
				AND REAL_TICKER_CONC_RSK NOT LIKE '%UKI-P5%' */
			
			GROUP BY 
				DATA_SOURCE
				, CUSIP
				, PORTF_LIST
				, CIC
				, COUNTERPARTY
				, TYPE_OF_EXPOSURE
				, SCOPE
				, PORTF_NAME
				, INC_GRP

			HAVING 
				SUM(MKT_VALUE_DIV_1000) <> 0.00	
		) TEMP

	GROUP BY 
		COUNTERPARTY_FIN
		, TYPE_OF_EXPOSURE
		, SCOPE
		, PORTF_NAME
		, INC_GRP

	ORDER BY 
	COUNTERPARTY_FIN
	;
QUIT;