PROC SQL ;

OPTIONS MISSING='';

/*Create Temp table to load the extracted Data*/

CREATE TABLE WORK.S1001_D5_IMT AS 


SELECT 


CASE WHEN XIP.PORTFOLIO_CLASSIFICATION = 'G' THEN '6 - General' ELSE XIP.PORTFOLIO_CLASSIFICATION END AS  C0040  , 
	

REP.FUND_NUMBER AS C0050 ,

CASE WHEN REP.ASSET_CATEGORY='7' THEN '7 - Cash and deposits' 
			ELSE REP.ASSET_CATEGORY
END AS C0060,

REP.COUNTERPARTY_NM AS C0070 ,

REP.COUNTERPARTY_LEI_CD AS C0080  , 

CASE WHEN REP.COUNTERPARTY_LEI_STATUS='1' THEN '1 - LEI'
			ELSE REP.COUNTERPARTY_LEI_STATUS
END AS C0090   ,

CASE WHEN REP.COLLATERAL_TYPE='1' THEN '1 - Government bonds' 
		     ELSE REP.COLLATERAL_TYPE
END AS C0100  ,		     

CASE WHEN XIP.UNIT_INDEX_LINKED_IND = 'N' THEN '2 - Neither unit-linked nor index-linked' ELSE '1 - Unit-linked or index-linked' END AS C0110, 
 
CASE WHEN REP.CONTRACT_POSITION = '2' THEN '2 - Seller in a repo' 
			ELSE REP.CONTRACT_POSITION 
END AS C0120,

REP.NEAR_LEG_AMT AS C0130 , 

REP.FAR_LEG_AMT AS C0140,

REP.START_DT AS C0150,

REP.MATURITY_DT AS C0160 ,

REP.SOLVENCY_II_VALUE AS C0170 ,

'Direct Line Insurance Group plc' AS C0010 ,

'213800FF2R23ALJQOP04' AS C0020, 

'1 - LEI' AS C0030 , 

REP.CUSIP AS INTERNAL_ID,

CASE WHEN SUBSTR(REP.CUSIP,1,3) = 'BRS' THEN 'Undertaking' ELSE '-' END AS INTERNAL_ID_TYPE ,

REP.PORTFOLIO_ID , 
	 			MONTH(&AS_AT_MTH) AS INT9 ,

				YEAR(&AS_AT_MTH) AS INT10


		FROM	

				test.X_REPO_SECURITY_LENDING REP

				INNER JOIN test.X_INVESTMENT_PORTFOLIO XIP
				ON (REP.PORTFOLIO_ID=XIP.PORTFOLIO_ID  			
						AND DATEPART(XIP.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
							AND DATEPART(XIP.VALID_TO_DTTM) > &AS_AT_MTH   )
	

  WHERE				
				DATEPART(REP.VALID_FROM_DTTM) <= &AS_AT_MTH  
				AND DATEPART(REP.VALID_TO_DTTM) > &AS_AT_MTH   
			
	;
QUIT;

				     			