PROC SQL ;

OPTIONS MISSING='';

/*Create Temp table to load the extracted Data*/

	CREATE TABLE WORK.S1001_D5_INVOKE AS 

		SELECT 

				CASE WHEN XIP.ENTITY_LEI_STATUS = '1' THEN 'LEI/'
							WHEN XIP.ENTITY_LEI_STATUS = '2' THEN 'SC/'
							ELSE 'None'
				END||XIP.ENTITY_LEI_CD AS C0020,

				CASE WHEN REP.FUND_NUMBER='Not Ring Fenced' THEN '' END AS C0050,

				XIP.ENTITY_NAME AS C0010,

				CASE WHEN XIP.PORTFOLIO_CLASSIFICATION = 'G' THEN '6' ELSE XIP.PORTFOLIO_CLASSIFICATION END AS C0040,

				CASE WHEN REP.ASSET_CATEGORY='7' THEN '7' 
							ELSE REP.ASSET_CATEGORY
				END AS C0060,

				REP.COUNTERPARTY_NM AS C0070,

				CASE WHEN REP.COUNTERPARTY_LEI_STATUS='1' THEN 'LEI/'
							ELSE REP.COUNTERPARTY_LEI_STATUS
				END||REP.COUNTERPARTY_LEI_CD  AS C0080,

				CASE WHEN REP.COLLATERAL_TYPE='1' THEN '1' 
						     ELSE REP.COLLATERAL_TYPE
				END AS C0100,

				CASE WHEN XIP.UNIT_INDEX_LINKED_IND = 'N' THEN '2' ELSE '1' END AS C0110,
				 
				CASE WHEN REP.CONTRACT_POSITION = '2' THEN '2' 
							ELSE REP.CONTRACT_POSITION 
				END  AS C0120,

				REP.NEAR_LEG_AMT AS C0130,

				REP.FAR_LEG_AMT AS C0140,

				REP.START_DT AS C0150,

				REP.MATURITY_DT AS C0160,

				REP.SOLVENCY_II_VALUE AS C0170,
				  
				/*INTERNAL COLUMNS*/

				REP.CUSIP AS CUSIP,

				CASE WHEN SUBSTR(REP.CUSIP,1,3) = 'BRS' THEN 'Undertaking' ELSE '-' END AS ID_TYP ,

				REP.PORTFOLIO_ID , 

	 			MONTH(&AS_AT_MTH) AS INT9 ,

				YEAR(&AS_AT_MTH) AS INT10


		FROM	

				test.X_REPO_SECURITY_LENDING REP

				INNER JOIN test.X_INVESTMENT_PORTFOLIO XIP
				ON (REP.PORTFOLIO_ID=XIP.PORTFOLIO_ID  			
						AND DATEPART(XIP.VALID_FROM_DTTM) <= &AS_AT_MTH                                                                                                                    
							AND DATEPART(XIP.VALID_TO_DTTM) > &AS_AT_MTH   )
	

  WHERE				
				DATEPART(REP.VALID_FROM_DTTM) <= &AS_AT_MTH  
				AND DATEPART(REP.VALID_TO_DTTM) > &AS_AT_MTH   
						     			
	
	;
QUIT;

