

/*********************** PASS PARAMETERS DURING EXECUTION ************************

-- %let AS_AT_MTH = &AS_AT_MTH - DD/MM/YYYY , PLEASE I/P  THE MONTH END DATE WHILST GENERATING THE REPORT

*********************** PASS PARAMETERS DURING EXECUTION ************************

*********************** 					IGT2                                                    ************************
***********************                     IGT2 - DERIVATIVES - V1   iNVOKE VERSION                ************************
***********************   		    	    AUTHOR - MANJUNATH BOOMINATH							************************
***********************  					RACF_ID - BMGS											************************
***********************                     EMAIL_ID - MANJUNATH.BOOMINATH@DIRECTLINEGROUP.CO.UK 	************************
***********************                     last Updated DT - 04/01/2022                            ************************/


PROC SQL;

OPTIONS MISSING='';

	CREATE TABLE WORK.IGT2_S3602_INV AS 


		SELECT 
			 IGT2.IGT_ID AS C0010,

			 	 CASE
					WHEN IGT2.INSTRUMENT_TYPE_CD = '99' THEN 'CAU/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '9'  THEN 'OCANNA/' 
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '8'  THEN 'FIGI/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '7'  THEN 'RIC/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '6'  THEN 'BBGID/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '5'  THEN 'BT/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '4'  THEN 'WKN/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '3'  THEN 'SEDOL/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '2'  THEN 'CUSIP/'
	 				WHEN IGT2.INSTRUMENT_TYPE_CD = '1'  THEN 'ISIN/'
	 				ELSE 'CHECK_X_EIOPA_CD'
	 				END||IGT2.INSTRUMENT_ID
	 				 AS C0080 ,

			CASE WHEN IGT2.INVESTOR_BUYER_LEI_STATUS = '1' THEN 'LEI/'
	 				WHEN IGT2.INVESTOR_BUYER_LEI_STATUS = '2' THEN 'SC/'
	 				ELSE  'CHECK_X_EIOPA_CD'
	 				END||IGT2.INVESTOR_BUYER_LEI_CD AS C0030 , 

	 	 	CASE WHEN IGT2.ISSUER_SELLER_LEI_STATUS = '1' THEN 'LEI/'
	 				WHEN IGT2.ISSUER_SELLER_LEI_STATUS = '2' THEN 'SC/'
	 				ELSE  'CHECK_X_EIOPA_CD'
	 				END||IGT2.ISSUER_SELLER_LEI_CD AS C0060 ,

			 IGT2.INVESTOR_BUYER_NM AS C0020,

			 IGT2.ISSUER_SELLER_NM AS C0050,

			 IGT2.TRANS_TYPE_CD AS C0100,

			 PUT(IGT2.TRANS_TRADE_DT,DDMMYY10.) AS C0110,

			 PUT(IGT2.MATURITY_DT,DDMMYY10.) AS C0120,

			 IGT2.NOTIONAL_CURRENCY_CD AS C0130,

			 IGT2.NOTIONAL_TRANS_AMT AS C0140,

			 IGT2.NOTIONAL_RPT_AMT AS C0150,

			 COALESCE(PUT(IGT2.COLLATERAL_VALUE,21.2),'') AS C0160 , 

			 IGT2.DRVTS_CD AS C0170 ,

			CASE 
				WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '99' OR IGT2.ASSET_LIAB_DRVT_ID LIKE '%Multiple assets%' THEN 'CAU/'
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '9' THEN 'OCANNA/' 
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '8' THEN 'FIGI/'
				WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '7' THEN 'RIC/'
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '6' THEN 'BBGID/'
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '5' THEN 'BT/'
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '4' THEN 'WKN/'
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '3' THEN 'SEDOL/'
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '2' THEN 'CUSIP/'
	 			WHEN IGT2.ASSET_LIAB_DRVT_ID_CD = '1' THEN 'ISIN/'
	 			ELSE 'CHECK_X_EIOPA_CD'
	 		END||IGT2.ASSET_LIAB_DRVT_ID AS C0180,

			 COALESCE(IGT2.COUNTERPARTY_NM,'') AS C0200 , 

			 COALESCE(IGT2.SWAP_DLVRD_INTEREST_RT,'') AS C0210,

		 	 COALESCE(IGT2.SWAP_RCVD_INTEREST_RT,'') AS C0220,

		 	 COALESCE(IGT2.SWAP_DLVRD_CURRENCY_CD,'') AS C0230 ,

			 COALESCE(IGT2.SWAP_RCVD_CURRENCY_CD,'') AS C0240

											  
		FROM 
			test.X_INTER_GRP_TRANS_DRVTS IGT2 

		WHERE 				
			IGT2.ASOF_DATE = &AS_AT_MTH
									
		ORDER BY 
		    C0010
		;
QUIT;