PROC SQL;

OPTIONS MISSING='';

CREATE TABLE WORK.D3_S0901_INV AS 

	SELECT 	
		
		CASE WHEN D3.UNDERTAKING_LEI_STATUS = '1' THEN 'LEI/' 
					WHEN  D3.UNDERTAKING_LEI_STATUS = '2' THEN 'SC/'  
						ELSE 'None' END || CASE WHEN  UNDERTAKING_LEI_STATUS NOT IN ('1','2') THEN '' ELSE UNDERTAKING_LEI END AS C0020 , 

		ENTITY_NAME	 AS C0010,

		D3.ASSET_CATEGORY AS C0040,
																			
	   CASE WHEN D3.PORTFOLIO_CD IN  ('G','6') THEN '6' ELSE D3.PORTFOLIO_CD END  AS C0050	,
	   
	   	CASE WHEN D3.RING_FENCED_FUND_FLAG IN ('N','2') THEN '2' 
								 WHEN D3.RING_FENCED_FUND_FLAG IN ('Y','1') THEN '1'
								 ELSE D3.RING_FENCED_FUND_FLAG END AS C0060 ,
								 
		SUM(D3.ACC_DIVIDENDS) AS  C0070,
		 
		SUM(D3.INTEREST)	 AS C0080 ,
		
		SUM(CASE WHEN  SUBSTR(D3.ASSET_CATEGORY,1,1)	= '9' THEN   D3.ACC_RENT  ELSE . END) AS C0090 FORMAT = 21.2 ,
		
		SUM(D3.NET_GAIN_AND_LOSSES)	AS C0100 FORMAT = 21.2,
		
		SUM(D3.UNRL_GAINS_AND_LOSSES) AS C0110 FORMAT = 21.2
		
	FROM 
		test.X_RETURN_ON_INVESTMENTS D3

	WHERE 
		D3.ASOF_DATE = &AS_AT_MTH		

	GROUP BY 
		C0020 , C0010	, C0040 , C0050, C0060
		
	ORDER BY 
		C0010,C0040		;

QUIT;	
			 