PROC SQL;

OPTIONS MISSING='';

CREATE TABLE WORK.D3_S0901_IMT AS 

	SELECT 
		ENTITY_NAME	 AS C0010,
		
		UNDERTAKING_LEI AS C0020,
		
		CASE WHEN D3.UNDERTAKING_LEI_STATUS = '1' THEN '1 - LEI' 
					WHEN  D3.UNDERTAKING_LEI_STATUS = '2' THEN '2 - SC' 
						ELSE '9 - None' END AS C0030 , 
		CASE 
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '1' THEN '1 - Government bonds'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '2' THEN '2 - Corporate bonds'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '3' THEN '3 - Equity'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)  = '4' THEN '4 - Collective Investment Undertakings'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '5' THEN '5 - Structured notes'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '6' THEN '6 - Collateralised securities'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '7' THEN '7 - Cash and deposits'	
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '8' THEN '8 - Mortgages and loans'	
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)	= '9' THEN '9 - Property'	
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)  = 'A' THEN 'A - Futures'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)  = 'D' THEN 'D - Swaps'
						WHEN SUBSTR(D3.ASSET_CATEGORY,1,1)  = 'E' THEN 'E - Forwards'
		 ELSE 
		CASE WHEN D3.ASSET_CATEGORY IS NULL OR D3.ASSET_CATEGORY='' THEN ' - ' 	ELSE SUBSTR(D3.ASSET_CATEGORY,1,1)	 END  
		END AS C0040,
																			
	   CASE WHEN D3.PORTFOLIO_CD IN  ('G','6') THEN '6 - General ' ELSE D3.PORTFOLIO_CD END  AS C0050	,
	   
	   	CASE WHEN D3.RING_FENCED_FUND_FLAG IN ('N','2') THEN '2 - Neither unit-linked nor index-linked' 
								 WHEN D3.RING_FENCED_FUND_FLAG IN ('Y','1') THEN '1- Unit-linked or index-linked'
								 ELSE D3.RING_FENCED_FUND_FLAG END AS C0060 ,
								 
		D3.ACC_DIVIDENDS AS  C0070,
		 
		D3.INTEREST	 AS C0080 ,
		
		CASE WHEN  SUBSTR(D3.ASSET_CATEGORY,1,1)	= '9' THEN   PUT(D3.ACC_RENT,25.2)  ELSE 'NOT - APPLICABLE' END AS C0090 ,
		
		D3.NET_GAIN_AND_LOSSES	AS C0100 FORMAT = 21.2,
		
		D3.UNRL_GAINS_AND_LOSSES AS C0110 FORMAT = 21.2
		
	FROM 
		test.X_RETURN_ON_INVESTMENTS D3

	WHERE 
		D3.ASOF_DATE = &AS_AT_MTH				
		
	ORDER BY 
		C0010,C0040		;

QUIT;	
			 